name: layerlens
version: 1.0.6
description: Generate a dependency diagram in every folder of your source code.
repository: https://github.com/polina-c/layerlens

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^3.0.0
  args: ^2.3.1
  cli_util: ^0.3.5
  http: ^0.13.5
  path: ^1.8.3
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
