name: layerlens
version: 1.0.16
description: Generate a dependency diagram in every folder of your source code.
repository: https://github.com/polina-c/layerlens

executables:
  layerlens:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: '>=5.4.0 <7.0.0'
  args: ^2.3.1
  platform: ^3.1.0
  path: ^1.8.2
  surveyor: ^1.0.0-dev.2.0
  meta: ^1.12.0
  glob: ^2.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
